# see how to configure things here in:
# https://cloud.google.com/appengine/docs/standard/python3/config/appref
runtime: python37

# NOTES:
# - we can add a section like this:
# - url: /app/.*
#   script: auto
#   secure: always
# but it turns out we don't need it so I cut it out
#
# - if you want to deploy a test version use ./gcloud/gcloud_deploy_test.sh
# the problem with this is that you will see the app on in
# [version].default.appspot.com
# which means that you cannot use https because he browser will complain
# which means that you have to remove all the "secure: always" entries below.
#
# - I didn't find a way to just say "secure: all" or something so to add and
# remove https you must add and remove all 'secure' tags attached to all url
# handers and add them back.
#
# - cache expiration time, default is 10 min
# watch out! you cannot remove stuff from the cache so avoid the temptation to
# put stuff in the cache for way too long. see document above.
# default_expiration: "10m"


automatic_scaling:
  max_instances: 2

handlers:
- url: /static/
  static_dir: static/
  secure: always
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  secure: always
- url: /
  static_files: static/html/index.html
  upload: static/html/index.html
  secure: always
